### ISSUE TITLE
[dotnet-httprepl] matching command not found when calling httprepl after the package was installed

### ISSUE THREAD

**Issue by metoly** [aspnet/HttpRepl#10]

**Comment by tlmii** [comment]
@metoly Going to close this for now since there's no more details and I'm guessing it won't be relevant anymore after we publish the new packages to nuget. Feel free to reopen if you disagree or have more information.

**Comment by bigswede74** [comment]
I have httprepl installed but I cant invoke the command. Am I missing a path variable?

'dotnet-httprepl' is not recognized as an internal or external command.

**Comment by tlmii** [comment]
Yes, it should be on your path after you've installed it, if you installed it globally. From a command line, run:

```
dotnet tool list --global
```
Does it list the package and command?

**Comment by bigswede74** [comment]
@tlmii Yes when I run that command it shows as installed.

C:\>dotnet tool list -g
Package Id                     Version                    Commands
-------------------------------------------------------------------------
microsoft.dotnet-httprepl      3.0.0-preview.19370.1      dotnet-httprepl

**Comment by tlmii** [comment]
Interesting. Next two things to check:

1. Take a look in your tools folder (probably `%userprofile%\.dotnet\tools\`) - do you see the dotnet-httprepl.exe shim in there? 
2. is that folder (`%userprofile%\.dotnet\tools\`) on your PATH?

**Comment by bigswede74** [comment]
@tlmii it was the PATH variable was missing, I'm not sure what happened but the install did not add it.

**Comment by tlmii** [comment]
Odd. That's done by the SDK itself, not the tool. From the [docs](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools):

> These locations are added to the user's path when the SDK is first run, so Global Tools installed there can be called directly.

I guess maybe something got gummed up with your sdk install? Glad you've got it working now.

**Comment by bigswede74** [comment]
@tlmii Any guidance on passing query string parameters using httprepl?

**Comment by tlmii** [comment]
@bigswede74 You can do it by just adding it to whatever call you're making. so for instance:

```
set base https://petstore.swagger.io/v2/
cd pet
cd 5
get ?myquerystring=5
```
Note of course that, in the example here, the querystring doesn't actually do anything. But it is passed to the server as expected. Same thing should work for `POST`, etc.

Since the tool was written with REST APIs in mind, the directory structure concept doesn't really lend itself well to APIs that require querystrings rather than having the parameters be part of the path. But it will work. 

If you have any follow up questions, please open a new issue so we can track it properly.

**Comment by bigswede74** [comment]
@tlmii Great thanks again.

**Comment by griffon251** [comment]
Fix for:
`'httprepl' is not recognized as an internal or external command,
operable program or batch file.`
and
`httprepl: The term 'httprepl' is not recognized as the name of a cmdlet, function, script file, or operable program.`
despite it running `dotnet tool list --global` and verifying that it is installed

1. Press the `Windows `key
2. Search for "Edit the system environment variables"
3. Under the 'Advanced' tab, select the `Environment Variables...` button
4. Under the 'System variables' table, double click on the 'Path' entry
5. Add a `New` entry
6. Enter `C:Program Files\dotnet\tools\
7. Press `OK`
8. Restart your terminal client

At least for me, this allowed for the terminal to recognize the `httprepl` command. Hope this helps!

**Comment by yeuliansymaeh** [comment]
for mac,it is:     export PATH=$PATH:/Users/{yourname}/.dotnet/tools
