### ISSUE TITLE
Text editor opens an empty file

### ISSUE THREAD

**Issue by jrCalcopietro** [aspnet/HttpRepl#131]
Hello guys,

I gave it a try and I really enjoyed it, but I have a little problem with 'POST' (and other verbs that send a body). 

My default text editor opens an empty file when it should open with a template based on my swagger.json, right?

I set my default editor with the command - pref set editor.command.default "{{text editor path}}" - and my swager exposes the template for operation as follow:
![image](https://user-images.githubusercontent.com/1273331/62319900-5e6ebe00-b475-11e9-9755-f46537b63a8b.png)

I dont know if this is a issue or a miss configuration.

Thank you.

**Comment by tlmii** [comment]
Yes, the tool should give you a template based on your swagger.json file.

Which swagger/openapi version are you using? 

Could you supply your whole swagger.json file? Or at least the sections relevant to that particular api call?

One thing to try is to use another api to see if it works there. For instance, try the following commands:

```
pref set editor.command.default "{{text editor path}}"
set base https://petstore.swagger.io/v2/
cd user
post
```

In my case, that opens up my editor with the following template:

```json
{
  "id": 0,
  "username": "",
  "firstName": "",
  "lastName": "",
  "email": "",
  "password": "",
  "phone": "",
  "userStatus": 0
}
```

Does that work for you? If not, we probably need to look at your swagger.sjon file and see if there is a reason we aren't detecting your endpoint as expected.

**Comment by tlmii** [comment]
@jrCalcopietro Just checking in to see if you had any more info here. Doing a bit of a bug bash so would like to take a look if you can provide any more details.

**Comment by tlmii** [comment]
Going to close this as no repro right now. If you're able to provide a repro for your situation, post back and we can take a look.
